name: movie_review_app
description: A modern premium movie review application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  youtube_player_iframe: ^5.2.2
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.6
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
